# Generated by Django 5.0 on 2025-06-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartner',
            old_name='company',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='phone',
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='affiliation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='sales_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='business_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businessapp.businesspartner'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='purchase_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
