# Generated by Django 5.0 on 2025-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0002_rename_company_businesspartner_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='sales_history',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
