# Generated by Django 5.0 on 2025-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0003_alter_businesspartner_sales_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, unique=True)),
                ('presentation_sent', models.BooleanField(default=False)),
                ('documents_received', models.BooleanField(default=False)),
                ('contract_sent', models.BooleanField(default=False)),
                ('contract_reviewed', models.BooleanField(default=False)),
                ('contract_signed', models.BooleanField(default=False)),
                ('parametrization_done', models.BooleanField(default=False)),
                ('training_done', models.BooleanField(default=False)),
                ('users_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
